// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiFlGfXX0GVd9uJrVYF7jf4IkkgJu8jiA',
    appId: '1:232979486767:web:c0ab60a7d57c6ad3dcceda',
    messagingSenderId: '232979486767',
    projectId: 'backendproject-d0ed8',
    authDomain: 'backendproject-d0ed8.firebaseapp.com',
    storageBucket: 'backendproject-d0ed8.appspot.com',
    measurementId: 'G-YNLZ6CHQ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdk1abmtaLm5XvyVBINzNajD06BNQOJxc',
    appId: '1:232979486767:android:669f4eeb91d4d00ddcceda',
    messagingSenderId: '232979486767',
    projectId: 'backendproject-d0ed8',
    storageBucket: 'backendproject-d0ed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlx0TMy2l3rbeXRhoCS7mJOdfg2Op1vNw',
    appId: '1:232979486767:ios:4ce3c30c501f77badcceda',
    messagingSenderId: '232979486767',
    projectId: 'backendproject-d0ed8',
    storageBucket: 'backendproject-d0ed8.appspot.com',
    iosClientId: '232979486767-8hdpiaakg16c9dfjjg1evfodr57vu5vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlx0TMy2l3rbeXRhoCS7mJOdfg2Op1vNw',
    appId: '1:232979486767:ios:4ce3c30c501f77badcceda',
    messagingSenderId: '232979486767',
    projectId: 'backendproject-d0ed8',
    storageBucket: 'backendproject-d0ed8.appspot.com',
    iosClientId: '232979486767-8hdpiaakg16c9dfjjg1evfodr57vu5vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.fproject',
  );
}
